/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminAcademicPerformanceRouteImport } from './routes/_authenticated/_admin/academic-performance'
import { Route as AuthenticatedAdminCoachesRouteImport } from './routes/_authenticated/_admin/coaches'
import { Route as AuthenticatedAdminHomepageRouteImport } from './routes/_authenticated/_admin/homepage'
import { Route as AuthenticatedAdminPerformanceDashboardRouteImport } from './routes/_authenticated/_admin/performance-dashboard'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminAcademicPerformanceRoute =
  AuthenticatedAdminAcademicPerformanceRouteImport.update({
    id: '/academic-performance',
    path: '/academic-performance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoachesRoute =
  AuthenticatedAdminCoachesRouteImport.update({
    id: '/coaches',
    path: '/coaches',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHomepageRoute =
  AuthenticatedAdminHomepageRouteImport.update({
    id: '/homepage',
    path: '/homepage',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerformanceDashboardRoute =
  AuthenticatedAdminPerformanceDashboardRouteImport.update({
    id: '/performance-dashboard',
    path: '/performance-dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academic-performance': typeof AuthenticatedAdminAcademicPerformanceRoute
  '/coaches': typeof AuthenticatedAdminCoachesRoute
  '/homepage': typeof AuthenticatedAdminHomepageRoute
  '/performance-dashboard': typeof AuthenticatedAdminPerformanceDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/academic-performance': typeof AuthenticatedAdminAcademicPerformanceRoute
  '/coaches': typeof AuthenticatedAdminCoachesRoute
  '/homepage': typeof AuthenticatedAdminHomepageRoute
  '/performance-dashboard': typeof AuthenticatedAdminPerformanceDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_admin/academic-performance': typeof AuthenticatedAdminAcademicPerformanceRoute
  '/_authenticated/_admin/coaches': typeof AuthenticatedAdminCoachesRoute
  '/_authenticated/_admin/homepage': typeof AuthenticatedAdminHomepageRoute
  '/_authenticated/_admin/performance-dashboard': typeof AuthenticatedAdminPerformanceDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/academic-performance'
    | '/coaches'
    | '/homepage'
    | '/performance-dashboard'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/academic-performance'
    | '/coaches'
    | '/homepage'
    | '/performance-dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/_admin/academic-performance'
    | '/_authenticated/_admin/coaches'
    | '/_authenticated/_admin/homepage'
    | '/_authenticated/_admin/performance-dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/academic-performance': {
      id: '/_authenticated/_admin/academic-performance'
      path: '/academic-performance'
      fullPath: '/academic-performance'
      preLoaderRoute: typeof AuthenticatedAdminAcademicPerformanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/coaches': {
      id: '/_authenticated/_admin/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof AuthenticatedAdminCoachesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/homepage': {
      id: '/_authenticated/_admin/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof AuthenticatedAdminHomepageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/performance-dashboard': {
      id: '/_authenticated/_admin/performance-dashboard'
      path: '/performance-dashboard'
      fullPath: '/performance-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminPerformanceDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAcademicPerformanceRoute: typeof AuthenticatedAdminAcademicPerformanceRoute
  AuthenticatedAdminCoachesRoute: typeof AuthenticatedAdminCoachesRoute
  AuthenticatedAdminHomepageRoute: typeof AuthenticatedAdminHomepageRoute
  AuthenticatedAdminPerformanceDashboardRoute: typeof AuthenticatedAdminPerformanceDashboardRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAcademicPerformanceRoute:
    AuthenticatedAdminAcademicPerformanceRoute,
  AuthenticatedAdminCoachesRoute: AuthenticatedAdminCoachesRoute,
  AuthenticatedAdminHomepageRoute: AuthenticatedAdminHomepageRoute,
  AuthenticatedAdminPerformanceDashboardRoute:
    AuthenticatedAdminPerformanceDashboardRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
