/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/_admin'
import { Route as AuthenticatedAdminDesempenoAcademicoRouteImport } from './routes/_authenticated/_admin/desempeno-academico'
import { Route as AuthenticatedAdminInicioRouteImport } from './routes/_authenticated/_admin/inicio'
import { Route as AuthenticatedAdminPanelDesempenoRouteImport } from './routes/_authenticated/_admin/panel-desempeno'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminDesempenoAcademicoRoute =
  AuthenticatedAdminDesempenoAcademicoRouteImport.update({
    id: '/desempeno-academico',
    path: '/desempeno-academico',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInicioRoute =
  AuthenticatedAdminInicioRouteImport.update({
    id: '/inicio',
    path: '/inicio',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPanelDesempenoRoute =
  AuthenticatedAdminPanelDesempenoRouteImport.update({
    id: '/panel-desempeno',
    path: '/panel-desempeno',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desempeno-academico': typeof AuthenticatedAdminDesempenoAcademicoRoute
  '/inicio': typeof AuthenticatedAdminInicioRoute
  '/panel-desempeno': typeof AuthenticatedAdminPanelDesempenoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/desempeno-academico': typeof AuthenticatedAdminDesempenoAcademicoRoute
  '/inicio': typeof AuthenticatedAdminInicioRoute
  '/panel-desempeno': typeof AuthenticatedAdminPanelDesempenoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/_admin/desempeno-academico': typeof AuthenticatedAdminDesempenoAcademicoRoute
  '/_authenticated/_admin/inicio': typeof AuthenticatedAdminInicioRoute
  '/_authenticated/_admin/panel-desempeno': typeof AuthenticatedAdminPanelDesempenoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/desempeno-academico' | '/inicio' | '/panel-desempeno'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/desempeno-academico' | '/inicio' | '/panel-desempeno'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/_admin/desempeno-academico'
    | '/_authenticated/_admin/inicio'
    | '/_authenticated/_admin/panel-desempeno'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/desempeno-academico': {
      id: '/_authenticated/_admin/desempeno-academico'
      path: '/desempeno-academico'
      fullPath: '/desempeno-academico'
      preLoaderRoute: typeof AuthenticatedAdminDesempenoAcademicoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/inicio': {
      id: '/_authenticated/_admin/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedAdminInicioRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/_admin/panel-desempeno': {
      id: '/_authenticated/_admin/panel-desempeno'
      path: '/panel-desempeno'
      fullPath: '/panel-desempeno'
      preLoaderRoute: typeof AuthenticatedAdminPanelDesempenoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminDesempenoAcademicoRoute: typeof AuthenticatedAdminDesempenoAcademicoRoute
  AuthenticatedAdminInicioRoute: typeof AuthenticatedAdminInicioRoute
  AuthenticatedAdminPanelDesempenoRoute: typeof AuthenticatedAdminPanelDesempenoRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminDesempenoAcademicoRoute:
    AuthenticatedAdminDesempenoAcademicoRoute,
  AuthenticatedAdminInicioRoute: AuthenticatedAdminInicioRoute,
  AuthenticatedAdminPanelDesempenoRoute: AuthenticatedAdminPanelDesempenoRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
